### ISSUE TITLE
Small Refactor

### ISSUE THREAD

**Issue by plazinicmilan** [lunovak13/najteziZadatakIKada#1]
https://github.com/lunovak13/najteziZadatakIKada/blob/7d44ef66a19b0d9de93af79212831040bc1942ca/napredniKalkulator/src/napredniKalkulator/BasicCalc.java#L11

Let's try to simplify this. You have lines 11 and 13 that are quite similar. The only difference is += and -=

What you can do if you have only += ?

**Comment by lunovak13** [comment]
treba da stavim ovo sve posle = da da bude jedna promenljiva je l?

**Comment by plazinicmilan** [comment]
I would do something like:

for (int i = 1; i < izraz.length(); i = i + 2) {
     int operation = izraz.charAt(i) == '+' ? 1 : -1;

     rezultat += operation * Integer.valueOf(String.valueOf(izraz.charAt(i + 1)));
}

I'm closing this issue
